Prepare 2.0.0 for release
Shopify/deprecation_toolkit pull request #59
Opened 2022-03-10 23:44 UTC by sambostock

This PR updates the gem version to 2.0.0 ahead of release.

It also adds release notes, since there weren't any, and incidentally bumps the development version of `activesupport` (due to running `bundle install`) by one security patch version.

As per release instructions...

### ⚠️ Before Merging
- [ ] Draft new release in GitHub

### ⚠️ After Merging
- [ ] Deploy via Shipit and verify in Rubygems
- [ ] Publish drafted release

2022-03-10 23:45 UTC, sambostock commented on CHANGELOG.md
> +## 2.0.0 (2022-03-11)
Probably won't get a review today, so I put in tomorrow's date for release. This should be updated before merging, if the release is on a different day.

2022-03-11 01:01 UTC, sambostock commented on CHANGELOG.md
> +* [#45](https://github.com/Shopify/deprecation_toolkit/pull/45): Handle two part Ruby 2.7 keyword argument deprecation warning. (@casperisfine)
On top of the changelog entries, these were also missing releases, which I've since created.

2022-03-14 19:41 UTC, rafaelfranca requested changes

2022-03-14 19:41 UTC, rafaelfranca commented on .github/CONTRIBUTING.md
> +## Releasing a new version
This project is open source, and only a small fraction of contributors can release, so this documentation doesn't belong to the CONTRIBUTING.md file. We can change a RELEASE.md file in the root though.

2022-03-16 22:03 UTC, rafaelfranca approved these changes

2022-03-16 22:03 UTC, merged